"""Added comments relationship to Question

Revision ID: 8056fcf9eea8
Revises: f29bd2bc9a56
Create Date: 2024-11-14 01:17:23.938339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8056fcf9eea8'
down_revision = 'f29bd2bc9a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))
        batch_op.alter_column('answer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('answer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
